language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t oliverrw93/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true oliverrw93/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-eu-west-2-141382722459"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY